name: tekber_markas
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.5.4"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  table_calendar: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.8
  share_plus: ^10.1.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.17.5 # Untuk database Firestore
  firebase_auth: 4.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Bagian ini untuk menambahkan asset gambar ke aplikasi
  assets:
    - lib/assets/images/
    - lib/assets/icons/