// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDedanxUVoQsmlJXwshLsHPdLrGchmhewY',
    appId: '1:227338599972:web:e929b2772601266465e2b1',
    messagingSenderId: '227338599972',
    projectId: 'tekber-markas',
    authDomain: 'tekber-markas.firebaseapp.com',
    storageBucket: 'tekber-markas.firebasestorage.app',
    measurementId: 'G-XYW3KS0BP5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVla9c53XjvVZiiwVjqNsEKy2DbJJn0I',
    appId: '1:227338599972:android:6e00636a618c665865e2b1',
    messagingSenderId: '227338599972',
    projectId: 'tekber-markas',
    storageBucket: 'tekber-markas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNifOrDfV08QX85ej4GBmkPuEmpWt7aCA',
    appId: '1:227338599972:ios:ae70fc4de34088a165e2b1',
    messagingSenderId: '227338599972',
    projectId: 'tekber-markas',
    storageBucket: 'tekber-markas.firebasestorage.app',
    iosBundleId: 'com.example.tekberMarkas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNifOrDfV08QX85ej4GBmkPuEmpWt7aCA',
    appId: '1:227338599972:ios:ae70fc4de34088a165e2b1',
    messagingSenderId: '227338599972',
    projectId: 'tekber-markas',
    storageBucket: 'tekber-markas.firebasestorage.app',
    iosBundleId: 'com.example.tekberMarkas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDedanxUVoQsmlJXwshLsHPdLrGchmhewY',
    appId: '1:227338599972:web:7712a6c461ababe565e2b1',
    messagingSenderId: '227338599972',
    projectId: 'tekber-markas',
    authDomain: 'tekber-markas.firebaseapp.com',
    storageBucket: 'tekber-markas.firebasestorage.app',
    measurementId: 'G-D9WP81JMW1',
  );
}
